api_platform:
    # The title of the API.
    title: 'SPMetadataAPI'

    # The description of the API.
    description: 'SAML2 service provider metadata registration API for a Shibboleth federation.'

    # The version of the API.
    version: '0.1.0'

    # The list of enabled formats. The first one will be the default.
    formats:
      jsonld:   ['application/ld+json']
      jsonhal:  ['application/hal+json']
      jsonapi:  ['application/vnd.api+json']
      json:     ['application/json']
      xml:      ['application/xml', 'text/xml']
      yaml:     ['application/x-yaml']
      csv:      ['text/csv']
      html:     ['text/html']
      myformat: ['application/xml']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    # Custom mapping
    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        #Custom mapping
        App\Exception\MetadataNotFoundException: 404
