api_platform:
    # The title of the API.
    title: 'SPMetadataAPI'

    # The description of the API.
    description: 'SAML2 service provider metadata registration API for a Shibboleth federation.'

    # The version of the API.
    version: '0.1.0'

    # The list of enabled formats. The first one will be the default.
    formats:
      jsonld:   ['application/ld+json']
      jsonhal:  ['application/hal+json']
      jsonapi:  ['application/vnd.api+json']
      json:     ['application/json']
      xml:      ['application/xml', 'text/xml']
      yaml:     ['application/x-yaml']
      csv:      ['text/csv']
      html:     ['text/html']
      myformat: ['application/xml']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
